yarnPath: .yarn/releases/yarn-rc.js
# https://next.yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-
packageExtensions:
  "docz-core@*"
    peerDependenciesMeta:
      "cross-spawn"
